[package]
name = "mtd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.27.0"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"